feat!: v2
* feat(core)!: v2

* feat(preact)!: drop deprecated recommended export

* feat(react)!: drop deprecated recommended export

* feat(solid)!: drop deprecated recommended export

* refactor(core): remove redundant module

* refactor(core): lint fix

* refactor(core): better typing for hooknametoid function

* refactor(react): js impl

* refactor(core): convert interfaces to type aliases

* refactor(preact): js impl

* refactor(qwik): js impl

* refactor(preact): remove redundant tsconfig

* refactor(react): remove redundant tsconfig

* refactor(qwik): remove redundant tsconfig

* refactor(solid): js impl

* refactor(recommended): js impl

* refactor(preact): remove redundant es6 env

* refactor(solid): remove redundant es6 env

* refactor: typescript-eslint updates

* refactor(docs): api-extractor

* refactor(docs): api-extractor

* refactor: prettier config update

* fix(core): revert rule to type alias

* ci(ci): fix docs dirty checking

* refactor(example-preact): v2 update

* refactor(example-qwik): v2 update

* refactor(example-react): v2 update

* refactor(example-solid): v2 update

* docs: introduction

* docs: fix link

* docs: intro demo link color

* docs: add migration guide

* docs: quickstart with no framework

* docs: configuration guide

* fix(core): make default cssproperties less restrictive

* docs: fix note syntax

* docs: migration guide fallback option

* docs(core): more complete documentation of debug option

* docs: configuration options

* docs: setup and usage

* docs: fix typo in setup article

* docs: react quickstart

* docs: fix debug flag

* docs: add solid quickstart

* docs: preact quickstart

* docs: qwikstart

* docs: solid quickstart vite

* feat(site)!: new website for v2

* refactor(site): v2 website

* refactor(site): docs max width

* refactor(site): quickstart and heading sizes

* refactor(site): codespan font size

* refactor(site): docs home

* refactor(site): diff highlighting cleanup

* refactor(site): meta

* refactor(site): blockquote formatting fix

* refactor(site): header links

* refactor(site): meta

* refactor(site): select docs icon when appropriate

* refactor(site): lint

* refactor(site): descriptions

* refactor(site): description (qwik)

* refactor(site): move router-head

* refactor(site): fix homepage links

* refactor: formatting

* ci: prettier version fix

* docs: update

* fix(example-solid): type issue in lib

* feat(core)!: rename match to on etc

* refactor(site): core api changes

* docs: core api updates

* feat(core): plain json hooks and cond styles

* docs(preact): update old reference to match fn

* refactor: remove unnecessary immutability

* refactor(site): light mode color fixes

* refactor(site): lint fix

* docs: docs update

* refactor(example-preact): core api changes

* refactor(example-qwik): core api changes

* refactor(example-react): core api changes

* refactor(example-solid): core api changes

* docs: readme updates for v2

* docs: fix configuration typo

* docs: fix csstype reference formatting

* docs: usage alternate syntax

* docs(coree): improve readability

* refactor(site): table display

* refactor(site): suggest edit link

* refactor(site): icon dimensions

* docs: fix defect in vanilla quickstart code

* refactor(site): em media queries

* refactor(site): testimonial card active color

* docs: update link

* docs: remove package list from main readme

* refactor: suggest edit doc layout

* docs: conclude intro with next steps

* refactor(site): add sans-serif fallback cls

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,10 +14,6 @@ jobs:
 
       - uses: wagoid/commitlint-github-action@v5
 
-      - uses: actionsx/prettier@v3
-        with:
-          args: --check .
-
       - uses: actions/setup-node@v3
         with:
           node-version: 20.5.0
@@ -25,11 +21,21 @@ jobs:
 
       - run: npm ci
 
+      - run: npx prettier --check .
+
       # Note that the packages must be built before linting. Otherwise, some
       # types will be inferred as `any` leading to errors.
       - run: npm run lint --workspaces --if-present
 
       - run: npm test --workspaces --if-present
+
+      # Ensure docs are up-to-date.
+      - run: npm run docs
+      - run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo 'Error: Git status is not clean.';
+            exit 1;
+          fi
 
       - run: npm run build --workspace=examples
 
