refactor(docs): api-extractor

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,6 +31,14 @@ jobs:
 
       - run: npm test --workspaces --if-present
 
+      # Ensure docs are up-to-date.
+      - run: npm run docs
+      - run: |
+          if test -n '$(git status --porcelain)'; then
+            echo 'Error: Git status is not clean.';
+            exit 1;
+          fi
+
       - run: npm run build --workspace=examples
 
       - run: npm run build --workspace=site
