breaking: declaration conflict protection
This change introduces type-level protection against using incompatible
properties in the same style object. For example, `margin` and `marginTop`
cannot be used across transforms because one declaration's fallback value
would overwrite the other's.

This constitutes a breaking change at the type level only. Most client
code should not need to be changed.

diff --git a/.github/workflows/next.yml b/.github/workflows/next.yml
--- a/.github/workflows/next.yml
+++ b/.github/workflows/next.yml
@@ -99,3 +99,22 @@ jobs:
             git status --porcelain docs/api
             exit 1
           fi
+
+  codegen:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version-file: .nvmrc
+          cache: npm
+      - run: npm ci
+      - run: npm run codegen --workspaces --if-present
+      - name: check
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo 'Error: Generated files are out of sync.'
+            echo 'Please run "npm run codegen --workspaces --if-present" locally and commit the updated files.'
+            git status --porcelain
+            exit 1
+          fi
